# Generated by Django 6.0.5 on 2026-09-11 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('condition_order', models.CharField(choices=[('pairwise_first', 'Pairwise first'), ('ranking_first', 'Ranking first')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('current_stage', models.CharField(default='intro', max_length=32)),
                ('pairwise_pairs', models.JSONField(blank=True, default=list)),
                ('ranking_sets', models.JSONField(blank=True, default=list)),
                ('evaluation_pairs', models.JSONField(blank=True, default=list)),
                ('pairwise_responses', models.JSONField(blank=True, default=list)),
                ('ranking_responses', models.JSONField(blank=True, default=list)),
                ('evaluation_responses', models.JSONField(blank=True, default=list)),
                ('questionnaire_responses', models.JSONField(blank=True, default=dict)),
                ('pairwise_weights', models.JSONField(blank=True, default=list)),
                ('ranking_weights', models.JSONField(blank=True, default=list)),
                ('pairwise_metrics', models.JSONField(blank=True, default=dict)),
                ('ranking_metrics', models.JSONField(blank=True, default=dict)),
                ('pairwise_time_seconds', models.FloatField(default=0.0)),
                ('ranking_time_seconds', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
